export const TEST_DISPATCH = 'TEST_DISPATCH';
export const GET_ERRORS = 'GET_ERRORS';
export const LOGGED_IN = 'LOGGED_IN';
export const UPDATE_EDITOR_TEXT = 'UPDATE_EDITOR_TEXT';
export const ADD_EDITOR = 'ADD_EDITOR';
export const HANDLE_NOTE_CLICK = 'HANDLE_NOTE_CLICK';
export const  GET_DATA = 'GET_DATA';
export const DONE_CHANGES = 'DONE_CHANGES';
//? contacts
export const GET_CONTACTS = 'GET_CONTACTS'; 
export const ADD_CONTACT = 'ADD_CONTACT';
export const SAVE_CONTACT = 'SAVE_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const HANDLE_CONTACT_CLICK = 'HANDLE_CONTACT_CLICK';
//? reminders
export const ADD_REMINDER = 'ADD_REMINDER';
export const SAVE_REMINDER = 'SAVE_REMINDER';
export const GET_REMINDER = 'GET_REMINDER';
export const HANDLE_REMINDER_CLICK = 'HANDLE_REMINDER_CLICK';
export const UPDATE_REMINDER = 'UPDATE_REMINDER';
export const HANDLE_DAY_PRESS = 'HANDLE_DAY_PRESS';
export const CLOSE_REMINDER ='CLOSE_REMINDER';
export const DELETE_REMINDER ='DELETE_REMINDER';
